### ISSUE TITLE
Unhanded Promise Rejection

### ISSUE THREAD

**Issue by zerosonesfun** [Freeedle/Essential-Audio-Player#3]
After clicking play button the browser dev console shows this error: Unhandled Promise Rejection: AbortError: The operation was aborted.

It does not provide a line/file. 

Player still works fine.

**Comment by Freeedle** [comment]
Finely observed.
And I wish this wouldn’t have to happen. But alas, I have to cause the error even intentionally, or else the player will not work under iOS. Perhaps in a future iOS version this will become unnecessary. I will keep an eye on that.
Sorry for that. Blame Apple...
But be sure that this error alert can be ignored, and the player is indeed working.

For those who want to know why:
It has to do with the principle that audio must be started by user interaction (which is good).
By clicking the play button a cascade of functions is set off to initialize, load, buffer and finally play the audio. During this process the iOS Safari apparently loses the connection to the initial user interaction and ultimatley blocks the audio to play. The only solution that helped (so far) is to start and immediately stop the player right after the user click, before any other operation, and this returns the error alert because in that moment there is no audio file connected yet.
One day there will be a version 2.0 with an entirely rebuilt architecture that will be much more elegant and avoids this problem.

**Comment by zerosonesfun** [comment]
Makes sense. Thank you for this amazing player! I've bundled it into a Flarum extension (forum software just in case you haven't heard of it): https://github.com/zerosonesfun/flarum-essential-audio

**Comment by Freeedle** [comment]
Cool.
I like it when others like it.
Enjoy it!

**Comment by yrammos** [comment]
@zerosonesfun thank you for a beautiful plugin. I am facing the same unhandled promise on macOS, albeit in a ReadyMag site. Your demos work fine. On my own (ReadyMag) website, however, audio is played back only once and does not resume after pausing. I know this is outside the scope of your work, but would appreciate any educated guesses you may have.

Thank you in advance!

**Comment by Freeedle** [comment]
Sorry, I never dealt with RedyMag. Basically, it should also work there. And quite certainly, the unhandled promise rejection issue is not the reason. But from afar and without seeing any code it's hard to tell why it's not working.
As this is not necessarily a matter of public interest: On the player's website you find a contact email address. Would you mind writing an email? If you send a link to your ReadyMag site, I might take a look into the issue.

**Comment by yrammos** [comment]
Very much appreciated, @Freeedle. I’ll send you a link as soon as the site is accessible via an external URL.

**Comment by yrammos** [comment]
@Freeedle the issue was automagically resolved in the public instance of my site. It may have been a side-effect of ReadyMag’s asynchronous rendering. Apologies for the false alarm, and thanks for your help.

**Comment by Freeedle** [comment]
Good news: the Unhandled Promise Rejection issue is resolved!
It now works without throwing errors in the newly released v2.0
