### ISSUE TITLE
Google Lighthouse Warning

### ISSUE THREAD

**Issue by matthewcobb** [Freeedle/Essential-Audio-Player#6]
Google Lighthouse is showing a warning that is related to the `touchstart` event listeners.

<img width="716" alt="image" src="https://github.com/Freeedle/Essential-Audio-Player/assets/6074189/34398ee0-f8dc-4a38-a497-dedb69126418">

It recommends adding `passive: true` to any touchstart event listeners:

`document.addEventListener('touchstart', onTouchStart, {passive: true})`

More info here: https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr

**Comment by Freeedle** [comment]
I get the point and even tried to implement it.
But: this prevents the player button from dragging because it is interpreted as scrolling. Not so cool.
Google Lighthouse is a little too sweeping in its judgement, and I prefer to leave it as it is. – The draggable player button is an essential feature of this little player.

**Comment by Freeedle** [comment]
Tried to implement it, but it has negative side effects that disturb the player’s functionality.
Have to take a deeper look into that.

**Comment by Freeedle** [comment]
Done. Built into the newly released v2.0!
As this has implications on the player’s behavior on mobile devices that may not be liked by everyone, it comes as an option. You can choose which way to go. Activate passive listeners by adding the attribute `data-passive` (no values) to the player `div`.
